### ISSUE TITLE
Host/Plugin bus layout communication

### ISSUE THREAD

**Issue by baconpaul** [free-audio/interop-tracker#1]
Hi!

I'm starting a thread here to discuss how hosts and plugins communicate on busses.

Surge (the synth) has the following bus topology

- No main input
- Zero or One stereo or mono auxiliary input
- One or Three stereo outputs

So that gives us the option on 8 configurations (4 input configurations * 2 output configurations).

It seems the CLAP api gives me two things I can do. I can advertise my maximum set of busses or I can implement the clap_audio_ports_config and enumerate all my possible configurations. But "all my possible configurations" could be a big list. Imagine if I have a sampler with between 1 and 8 stereo or mono outputs and 0, 1, or 2 inputs. That would mean I provide, what, 24 possible configurations and auto generate names for them?

It seems VST3 has a slightly different semantic. It asks for bus count and then info but then does a bus by bus activation. When I load the surge xt vst3 in reaper, for instance, it says 'i can support 1 or 3 outputs which do i want' then activates or doesn't activate. Similarly when I load it in logic I see this

<img width="547" alt="Screen Shot 2022-01-30 at 8 48 01 AM" src="https://user-images.githubusercontent.com/13387561/151702435-36c0f9a0-0539-4d44-a80c-aee625a83dd9.png">

or with pianoteq this

<img width="592" alt="Screen Shot 2022-01-30 at 8 48 10 AM" src="https://user-images.githubusercontent.com/13387561/151702441-69b241f4-76d0-4ece-8e58-8e4e7cb7d878.png">

There's an additional complexity also, which is I don't quite see how to make a `clap_audio_port_info` represent a port which is currently not enabled. When you do a raw scan of surge, the answer you get is no main in, one aux in, one enabled main stereo out, two non-enabled aux stereo outs. So if a manufacturer never calls the port config extension should I return 1 or 3 for bus outputs? And for my buses which are not enabled, do I return channel count 0 and port type nullptr?

All ears on what the expected hand shakes are in these situations, but all three of surge, surge fx and (later this year) short circuit will need to deal with this so hoping I can get it write in the juce wrapper.

Thanks!

**Comment by abique** [comment]
Hi,

The config should be a relatively small list, because it is meant to be displayed to the user and it is **flat** (we could use `/` for adding level like with the params modules).

VST3 approach also has problems, because the plugin browser will show you N times the same plugin, one time per port configuration, see waves plugins. Also switching from one config to another will loose the state, as you need to re-create the plugin.

Port enabled: I see minor benefit to it. You'll have to activate/de-activate in order to enable a port, which may stop the sound and reset the processing state (filter state, ...). If the port is receiving silent audio, you'll have a buffer with the compress flag set and the value 0. I believe there can be a fast path in the plugin for such situation.

Now regarding the port configuration, you can also take the example of a MxNxPxQxR which could quickly expand to thousand of combination. To deal with that, the plugin should offer a way to the user to configure the port layout within the plugin GUI, and then ask the host to scan again.

Here is my rationale:
- simple possibilities fit well within the port config extension
- complex possibilities needs to be explained in the plugin manual, and it is better if you have a single explanation which works with every DAW. If the DAW has to do it for you, then you can't explain it once, you'll have to explain how to configure the ports for every major DAW (and keep track of DAW update/ui change). Also it is possible that some ports are linked with others for example if you set a given port to mono, then it implies that a set of other ports becomes mono as well. Those kind of rules would be very complicated to express to the daw. The plugin is the most likely to be able to offer a useful GUI for complex port configuration given that ports are often related to each others, and the task's complexity could be reduced.

In you case, I'd keep it simple:
- just one config:
  - one input (always, and it could also be always stereo, up to you)
  - three stereo out (always)
- in the plugin gui, I'd add a switch for the audio input to work in mono or stereo

This would have the advantage to let the host and plugin to route audio at anytime.

I don't think that the hypothetical optimization you'd achieve by having less ports (in your case) would bring much. But I may be wrong.

What do you think?

Alex

**Comment by baconpaul** [comment]
always stereo in is a problem because some people use a microphone input which is monophonic. so definitely have a 2x there. But far more importantly, the input is a side chain. It is almost always inactivated and the DAW informs us when the user has hooked a side chain up. You'll see in logic there the create time has output busses only and the side chain selection comes later. It's definitely the case that the 'turn on side chain' action changes the bus structure of the running plugin from the DAW, and there's no action the plugin can take to ask the DAW for that. And we do run different codepaths if it is routed in or not.

On the output structure we really usually don't want the extra busses (they are isolated scenes) and some daws do nutty things like 'if they are on default mix them against the master into stereo' (FL!)

And, somewhat less importantly, but still relevant this is sort of not how juce works. Juce plugins just advertise whether a bus layout is acceptable and then get asked by the host. You actually implement 'can I support X' and then get probed. So this seems to be a pretty big flip from common practice.

In surge, here's where we describe our maximum bus config:

https://github.com/surge-synthesizer/surge/blob/2fa82e8d4e92cc81463b9cc12c1d706b8faf35d0/src/surge-xt/SurgeSynthProcessor.cpp#L21

and here's where we confirm if the layout is valid

https://github.com/surge-synthesizer/surge/blob/2fa82e8d4e92cc81463b9cc12c1d706b8faf35d0/src/surge-xt/SurgeSynthProcessor.cpp#L180

Then we end up writing defensive code around the layout at process time

https://github.com/surge-synthesizer/surge/blob/2fa82e8d4e92cc81463b9cc12c1d706b8faf35d0/src/surge-xt/SurgeSynthProcessor.cpp#L275

and I think that's a pretty common pattern. I think I can, from those APIs, infer possible layouts (I mean I guess I know I can because JUCE does otherwise I wouldn't see the AU wrapper above, which at least shows output patterns)

I sort of wonder a bit also (and am not sure) if "change my plugin because it's a clap" is something we should look closely at. And we've been able to make surge work in all these settings without having to put in place an in-plugin ui.

Sorry for a bit of stream of consciousness but I think this one is a bit tricky. I like your suggestion but I wonder if it is far from where folks are today.

**Comment by baconpaul** [comment]
Alex and I chatted and sorted this out! Closing it and will write some code this week.
